import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { createManualCrop, getImagePrepState, getProjectRevision, inspectDataset, setAllImageInclusion, setAssetImageTransform, setGlobalImageTransform, setImageInclusion, setTrainingResolution, type ImagePrepState, type ImageTransform, type TrainingResolutionPolicy } from "../api";
import { useSession } from "../session";

type Filter = "all" | "included" | "excluded";
const ASPECTS = ["16:9", "1:1", "4:5", "5:4", "9:16"];
const MP_PRESETS = [0.25, 0.5, 0.75, 1.0, 1.5];
function aspectNumber(value: string) { const [w, h] = value.split(":").map(Number); return w > 0 && h > 0 ? w / h : 1; }

export function ImagePrepPage() {
  const navigate = useNavigate();
  const { project, revision, setRevision, dataset, setDataset, modelFamily } = useSession();
  const [prep, setPrep] = useState<ImagePrepState | null>(null); const [selected, setSelected] = useState<Set<string>>(new Set()); const [filter, setFilter] = useState<Filter>("all"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [editName, setEditName] = useState(""); const [globalDraft, setGlobalDraft] = useState<ImageTransform>({}); const [resolutionDraft, setResolutionDraft] = useState<TrainingResolutionPolicy>({ max_megapixels: 1, enable_bucket: true, bucket_no_upscale: true, dimension_step: 16 }); const [overrideDraft, setOverrideDraft] = useState<ImageTransform>({}); const [manualParent, setManualParent] = useState(""); const [manualAspect, setManualAspect] = useState("1:1"); const [manualCenterX, setManualCenterX] = useState(0.5); const [manualCenterY, setManualCenterY] = useState(0.5); const [manualScale, setManualScale] = useState(0.8); const [manualDims, setManualDims] = useState({ width: 1, height: 1 });
  useEffect(() => { if (!project || !revision) return; getImagePrepState(project.id, revision.id).then((state) => { setPrep(state); setGlobalDraft(state.global_transform || {}); setResolutionDraft(state.training_resolution); }).catch((err) => setMessage(err instanceof Error ? err.message : "Unable to load image prep state")); }, [project, revision]);
  const assets = prep?.assets ?? revision?.assets ?? []; const includedAssets = assets.filter((asset) => asset.included !== false); const sourceAssets = includedAssets.filter((asset) => asset.asset_kind !== "derived"); const visible = useMemo(() => assets.filter((asset) => filter === "all" || (filter === "included" ? asset.included !== false : asset.included === false)), [assets, filter]); const transformed = includedAssets; const editAsset = transformed.find((asset) => asset.filename === editName); const manualAsset = sourceAssets.find((asset) => asset.filename === manualParent) ?? sourceAssets[0]; const manualImage = dataset?.images.find((image) => image.filename === manualAsset?.filename);
  useEffect(() => { if (!manualParent && sourceAssets[0]) setManualParent(sourceAssets[0].filename); }, [manualParent, sourceAssets]);
  function toggle(filename: string) { setSelected((current) => { const next = new Set(current); if (next.has(filename)) next.delete(filename); else next.add(filename); return next; }); }
  async function refreshAll() { if (!project || !revision) return; const nextRevision = await getProjectRevision(project.id, revision.id); setRevision(nextRevision); const state = await getImagePrepState(project.id, revision.id); setPrep(state); setGlobalDraft(state.global_transform || {}); setResolutionDraft(state.training_resolution); setDataset(await inspectDataset(nextRevision.files_path)); }
  async function setIncluded(included: boolean) { if (!project || !revision || !selected.size) return; setBusy(true); try { setPrep(await setImageInclusion(project.id, revision.id, [...selected], included)); await refreshAll(); setMessage(`${selected.size} image(s) ${included ? "included" : "excluded"}.`); setSelected(new Set()); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to update working set"); } finally { setBusy(false); } }
  async function setAll(included: boolean) { if (!project || !revision) return; setBusy(true); try { setPrep(await setAllImageInclusion(project.id, revision.id, included)); await refreshAll(); setSelected(new Set()); } finally { setBusy(false); } }
  async function saveGlobalTransform() { if (!project || !revision) return; setBusy(true); try { const state = await setGlobalImageTransform(project.id, revision.id, globalDraft); setPrep(state); setGlobalDraft(state.global_transform); setMessage("Composition and image-adjustment recipe saved."); } finally { setBusy(false); } }
  async function saveResolution() { if (!project || !revision) return; setBusy(true); try { const state = await setTrainingResolution(project.id, revision.id, resolutionDraft); setPrep(state); setResolutionDraft(state.training_resolution); setMessage(`Maximum training resolution set to ${state.training_resolution.max_megapixels} MP with ${state.training_resolution.bucket_no_upscale ? "downscale-only" : "upscaling allowed"}.`); } catch (err) { setMessage(err instanceof Error ? err.message : "Unable to save training resolution"); } finally { setBusy(false); } }
  function openEditor(filename: string) { if (editName === filename) { setEditName(""); return; } const asset = transformed.find((item) => item.filename === filename); setEditName(filename); setOverrideDraft(asset?.transform_override || {}); }
  async function saveOverride() { if (!project || !revision || !editAsset) return; setBusy(true); try { setPrep(await setAssetImageTransform(project.id, revision.id, editAsset.filename, overrideDraft)); await refreshAll(); } finally { setBusy(false); } }
  async function resetOverride() { if (!project || !revision || !editAsset) return; setBusy(true); try { setPrep(await setAssetImageTransform(project.id, revision.id, editAsset.filename, {})); setOverrideDraft({}); await refreshAll(); } finally { setBusy(false); } }
  function manualCropRect() { const target = aspectNumber(manualAspect); const source = manualDims.width / Math.max(1, manualDims.height); let width: number; let height: number; if (source >= target) { height = manualScale; width = manualScale * target / source; } else { width = manualScale; height = manualScale * source / target; } const x = Math.min(1 - width, Math.max(0, manualCenterX - width / 2)); const y = Math.min(1 - height, Math.max(0, manualCenterY - height / 2)); return { x, y, width, height }; }
  async function addManualDerivative() { if (!project || !revision || !manualAsset) return; setBusy(true); try { const result = await createManualCrop(project.id, revision.id, manualAsset.filename, manualAspect, manualCropRect()); setPrep(result.state); await refreshAll(); setMessage(`${result.asset.filename} created; it now needs a caption.`); } finally { setBusy(false); } }
  if (!project || !revision || !dataset) return <section className="panel hero-panel stack"><p className="eyebrow">Project required</p><h1>Image Prep</h1><p className="muted">Open a project and choose a model-specific working dataset first.</p></section>;
  const included = prep?.included_count ?? includedAssets.length; const excluded = prep?.excluded_count ?? assets.length - included; const derivatives = prep?.derivative_count ?? 0; const manualRect = manualCropRect(); const targetAspect = globalDraft.aspect_ratio || "16:9"; const resolutionRows = prep?.resolution_assets ?? []; const downscaled = resolutionRows.filter((r) => r.direction === "downscale").length; const native = resolutionRows.filter((r) => r.direction === "native").length; const lowDetail = resolutionRows.filter((r) => r.low_detail).length;
  return <div className="stack image-prep-page">
    <header className="page-header"><div><p className="eyebrow">{project.name} · {revision.name}</p><h1>Build the Training Dataset</h1><p className="muted">Preserve useful source detail here; training resolution is a separate, non-destructive bucket policy.</p></div><div className="prep-counts"><span><strong>{assets.length}</strong> assets</span><span className="status-good"><strong>{included}</strong> working</span><span><strong>{derivatives}</strong> derived</span><span className="status-suspect"><strong>{excluded}</strong> excluded</span></div></header>
    {message && <div className="notice success">{message}</div>}
    <section className="panel stack"><div className="prep-section-heading"><div><p className="eyebrow">Stage 1</p><div className="card-title">Incoming Batch</div><p className="muted">Choose the images that belong to this project working set.</p></div><div className="actions"><button className="secondary" onClick={() => setAll(true)}>Include all</button><button className="secondary" onClick={() => setAll(false)}>Exclude all</button></div></div><div className="prep-toolbar"><div className="segmented"><button className={filter === "all" ? "selected" : ""} onClick={() => setFilter("all")}>All {assets.length}</button><button className={filter === "included" ? "selected" : ""} onClick={() => setFilter("included")}>Working {included}</button><button className={filter === "excluded" ? "selected" : ""} onClick={() => setFilter("excluded")}>Excluded {excluded}</button></div></div><div className="prep-grid">{visible.map((asset) => { const image = dataset.images.find((item) => item.filename === asset.filename); if (!image) return null; return <button key={asset.filename} className={`prep-image-card ${selected.has(asset.filename) ? "selected" : ""} ${asset.included === false ? "excluded" : ""}`} onClick={() => toggle(asset.filename)}><div className="prep-image-wrap"><img src={image.image_url} alt={asset.filename} />{asset.asset_kind === "derived" && <span className="derived-badge">Derived</span>}</div><div className="prep-image-meta"><strong>{asset.filename}</strong></div></button>; })}</div><div className="selection-bar"><span><strong>{selected.size}</strong> selected</span><div className="actions"><button className="secondary" disabled={!selected.size} onClick={() => setIncluded(false)}>Exclude selected</button><button className="primary" disabled={!selected.size} onClick={() => setIncluded(true)}>Include selected</button></div></div></section>
    <section className="panel stack"><div className="prep-section-heading"><div><p className="eyebrow">Stage 2</p><div className="card-title">Create Derivatives</div><p className="muted">Keep project derivatives at useful source resolution. Trainer resolution is applied later.</p></div></div><div className="manual-crop-layout"><div className="stack"><label>Parent image<select value={manualAsset?.filename || ""} onChange={(e) => setManualParent(e.target.value)}>{sourceAssets.map((a) => <option key={a.filename}>{a.filename}</option>)}</select></label><div className="manual-crop-preview">{manualImage && <><img src={manualImage.image_url} alt="" onLoad={(e) => setManualDims({ width: e.currentTarget.naturalWidth, height: e.currentTarget.naturalHeight })}/><div className="crop-mask"><div className="crop-box" style={{ left:`${manualRect.x*100}%`, top:`${manualRect.y*100}%`, width:`${manualRect.width*100}%`, height:`${manualRect.height*100}%` }}/></div></>}</div></div><div className="stack manual-crop-controls"><label>Aspect<select value={manualAspect} onChange={(e)=>setManualAspect(e.target.value)}>{ASPECTS.map(a=><option key={a}>{a}</option>)}</select></label><label>Crop size<input type="range" min="0.2" max="1" step="0.01" value={manualScale} onChange={(e)=>setManualScale(Number(e.target.value))}/></label><label>Horizontal<input type="range" min="0" max="1" step="0.01" value={manualCenterX} onChange={(e)=>setManualCenterX(Number(e.target.value))}/></label><label>Vertical<input type="range" min="0" max="1" step="0.01" value={manualCenterY} onChange={(e)=>setManualCenterY(Number(e.target.value))}/></label><button className="primary" onClick={addManualDerivative}>Create {manualAspect} derivative</button></div></div></section>
    <section className="panel stack"><div className="prep-section-heading"><div><p className="eyebrow">Stage 3A</p><div className="card-title">Composition & Adjustments</div><p className="muted">These describe the visual asset. They do not define training pixel cost.</p></div></div><div className="global-transform-grid"><label>Aspect<select value={targetAspect} onChange={(e)=>setGlobalDraft({...globalDraft,aspect_ratio:e.target.value})}>{ASPECTS.map(a=><option key={a}>{a}</option>)}</select></label><label>Crop mode<select value={globalDraft.crop_mode??"fill"} onChange={(e)=>setGlobalDraft({...globalDraft,crop_mode:e.target.value as "fill"|"fit"})}><option value="fill">Fill / crop</option><option value="fit">Fit</option></select></label><label>Exposure<input type="number" step="0.1" value={globalDraft.exposure??0} onChange={(e)=>setGlobalDraft({...globalDraft,exposure:Number(e.target.value)})}/></label><label>Brightness<input type="number" step="0.05" value={globalDraft.brightness??0} onChange={(e)=>setGlobalDraft({...globalDraft,brightness:Number(e.target.value)})}/></label><label>Contrast<input type="number" step="0.05" value={globalDraft.contrast??0} onChange={(e)=>setGlobalDraft({...globalDraft,contrast:Number(e.target.value)})}/></label><label>Gamma<input type="number" step="0.05" value={globalDraft.gamma??1} onChange={(e)=>setGlobalDraft({...globalDraft,gamma:Number(e.target.value)})}/></label></div><button className="primary" onClick={saveGlobalTransform}>Save composition recipe</button></section>
    <section className="panel stack training-resolution-panel"><div className="prep-section-heading"><div><p className="eyebrow">Stage 3B · Trainer policy</p><div className="card-title">Maximum Training Resolution</div><p className="muted">Musubi-style aspect buckets under one maximum pixel budget. Downscale-only is the safe default: small crops are never enlarged to pretend they contain more detail.</p></div><span className="badge">{modelFamily === "krea2" ? "Krea 2" : "Klein"}</span></div><div className="segmented">{MP_PRESETS.map(mp=><button key={mp} className={resolutionDraft.max_megapixels===mp?"selected":""} onClick={()=>setResolutionDraft({...resolutionDraft,max_megapixels:mp})}>{mp} MP</button>)}</div><div className="form-row"><label>Custom maximum MP<input type="number" min="0.05" max="8" step="0.05" value={resolutionDraft.max_megapixels} onChange={(e)=>setResolutionDraft({...resolutionDraft,max_megapixels:Number(e.target.value)})}/></label><label className="inline-check"><input type="checkbox" checked={resolutionDraft.enable_bucket} onChange={(e)=>setResolutionDraft({...resolutionDraft,enable_bucket:e.target.checked})}/> Aspect-ratio bucketing</label><label className="inline-check"><input type="checkbox" checked={resolutionDraft.bucket_no_upscale} onChange={(e)=>setResolutionDraft({...resolutionDraft,bucket_no_upscale:e.target.checked})}/> Never upscale source detail</label></div><div className="summary-grid"><div><span>Downscaled</span><strong>{downscaled}</strong></div><div><span>Native / below maximum</span><strong>{native}</strong></div><div><span>Low-detail warnings</span><strong>{lowDetail}</strong></div></div>{!resolutionDraft.bucket_no_upscale && <div className="notice error">Upscaling is enabled. This can manufacture pixels for crops below the requested training budget; use only deliberately.</div>}<button className="primary" onClick={saveResolution}>Save training resolution policy</button><div className="prep-grid">{resolutionRows.map(row=>{ const image=dataset.images.find(i=>i.filename===row.filename); if(!image)return null; return <div className="prep-image-card" key={row.filename}><div className="prep-image-wrap"><img src={image.image_url} alt={row.filename}/>{row.low_detail&&<span className="derived-badge">Low detail</span>}</div><div className="prep-image-meta"><strong>{row.filename}</strong><span>{row.source_width}×{row.source_height} · {row.source_megapixels} MP</span><span className={row.low_detail?"status-suspect":"status-good"}>→ {row.bucket_width}×{row.bucket_height} · {row.bucket_megapixels} MP · {row.direction}</span></div></div>;})}</div></section>
    <section className="panel stack"><div className="prep-section-heading"><div><div className="card-title">Per-image Exceptions</div><p className="muted">Click an image to adjust framing or tone without changing the global recipe.</p></div></div><div className="processed-grid">{transformed.map(asset=>{const image=dataset.images.find(i=>i.filename===asset.filename);if(!image)return null;const active=editName===asset.filename;return <div key={asset.filename} className="processed-grid-item"><button className={`processed-card ${active?"selected":""}`} onClick={()=>openEditor(asset.filename)}><div className="processed-image" style={{aspectRatio:aspectNumber(targetAspect)}}><img src={image.image_url} alt={asset.filename}/></div><div className="prep-image-meta"><strong>{asset.filename}</strong></div></button>{active&&<div className="inline-image-editor"><div className="inline-editor-preview"><img src={image.image_url} alt="" style={{objectPosition:`${(overrideDraft.crop_x??globalDraft.crop_x??.5)*100}% ${(overrideDraft.crop_y??globalDraft.crop_y??.5)*100}%`}}/></div><div className="stack inline-editor-controls"><label>Crop horizontal<input type="range" min="0" max="1" step="0.01" value={overrideDraft.crop_x??globalDraft.crop_x??.5} onChange={(e)=>setOverrideDraft({...overrideDraft,crop_x:Number(e.target.value)})}/></label><label>Crop vertical<input type="range" min="0" max="1" step="0.01" value={overrideDraft.crop_y??globalDraft.crop_y??.5} onChange={(e)=>setOverrideDraft({...overrideDraft,crop_y:Number(e.target.value)})}/></label><div className="form-row"><label>Exposure<input type="number" step="0.1" value={overrideDraft.exposure??""} onChange={(e)=>setOverrideDraft({...overrideDraft,exposure:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>Gamma<input type="number" step="0.05" value={overrideDraft.gamma??""} onChange={(e)=>setOverrideDraft({...overrideDraft,gamma:e.target.value===""?undefined:Number(e.target.value)})}/></label></div><div className="actions"><button className="secondary" onClick={resetOverride}>Reset</button><button className="primary" onClick={saveOverride}>Save override</button></div></div></div>}</div>;})}</div><div className="actions"><button className="primary" disabled={!included||busy} onClick={()=>navigate("/captions")}>Continue to Captions →</button></div></section>
  </div>;
}
