export type DatasetImage = { filename: string; caption: string; has_caption: boolean; image_url: string };
export type DatasetInfo = { id: string; path: string; image_count: number; caption_count: number; missing_caption_count: number; images: DatasetImage[] };
export type ProjectRevisionSummary = { id: string; name: string; model_family: string; basis: { type: string; id: string }; created_at: string; image_count: number; path: string; scratch: true };
export type ProjectRunSummary = { id: string; name: string; created_at: string; status: string; model_family: string; dataset_revision: string; path: string };
export type ProjectInfo = { id: string; name: string; description: string; trigger_word: string; created_at: string; updated_at: string; external_source: { path: string; owned_by_project: false; mutable_by_project: false }; imports: Array<{ id: string; created_at: string; image_count: number; path: string }>; current_import: string; current_dataset_revision: string | null; current_run: string | null; dataset_revisions: ProjectRevisionSummary[]; runs: ProjectRunSummary[] };
export type ImageTransform = { aspect_ratio?: string; crop_mode?: "fill" | "fit"; crop_x?: number; crop_y?: number; crop_scale?: number; exposure?: number; brightness?: number; contrast?: number; gamma?: number };
export type TrainingResolutionPolicy = { max_megapixels: number; enable_bucket: boolean; bucket_no_upscale: boolean; dimension_step: number };
export type ResolutionAsset = { filename: string; file_width: number; file_height: number; file_megapixels: number; crop_box: number[]; crop_width: number; crop_height: number; crop_megapixels: number; effective_transform: ImageTransform; source_width: number; source_height: number; source_megapixels: number; bucket_width: number; bucket_height: number; bucket_megapixels: number; linear_scale: number; direction: "downscale" | "native" | "upscale"; low_detail: boolean };
export type FaceCropProposal = { id: string; filename: string; asset_id?: string; face_index: number; score: number; face_bbox: number[]; crop_box: number[]; normalized_crop: { x: number; y: number; width: number; height: number }; aspect_ratio: string; padding_percent: number; source_width: number; source_height: number; preview_url?: string; basis?: Record<string, unknown> };
export type ProjectAsset = { id?: string; filename: string; caption: string; caption_sha256?: string; caption_updated_at?: string; origin?: string; parent_asset_id?: string | null; parent_filename?: string; operations?: Array<Record<string, unknown>>; included?: boolean; asset_kind?: "source" | "derived"; transform_override?: ImageTransform; baked_transform?: Record<string, unknown> };
export type ProjectRevision = { id: string; name: string; model_family: string; created_at: string; basis: { type: string; id: string }; scratch: true; files_path: string; global_transform?: ImageTransform; training_resolution?: TrainingResolutionPolicy; assets: ProjectAsset[] };
export type ImagePrepState = { revision: string; model_family: string; incoming_count: number; source_count?: number; included_count: number; excluded_count: number; derivative_count: number; face_derivative_count?: number; manual_derivative_count?: number; override_count?: number; global_transform: ImageTransform; training_resolution: TrainingResolutionPolicy; resolution_assets: ResolutionAsset[]; assets: ProjectAsset[] };
export type ProjectCreateResult = { project: ProjectInfo; revision: ProjectRevision };
export type RunInfo = { id: string; name: string; created_at: string; updated_at?: string; started_at?: string; completed_at?: string; failed_at?: string; error?: string; status: string; project_id: string; model_family: string; trigger_word: string; dataset_revision: string; dataset_path: string; dataset_is_scratch: true; output_dir: string; config: Record<string, unknown>; software: Record<string, unknown>; artifacts: Array<Record<string, unknown>>; telemetry_mode?: string; final_lora?: string | null; model_manifest?: Record<string, unknown> };
export type TrainingMetric = { type?: string; epoch: number; step_in_epoch?: number; loss: number; loss_moving_average: number };
export type PerImageLossRow = { epoch: number; step: number; key: string; t: number; loss: number; residual: number; ema: number; t_bucket?: number; t_bucket_mean?: number; batch?: number };
export type DecisionImageState = { verdict?: string; multiplier?: number; recommended_multiplier?: number; mean_residual?: number; mean_loss?: number; slope?: number; first?: number; last?: number; se?: number; trend_epochs?: number; baseline?: number; total_drop?: number; epochs?: number; improving?: boolean; release_votes?: number; stuck_epochs?: number };
export type DecisionSnapshot = { type: string; epoch: number; improving_count: number; plateaued: boolean; pending_count: number; best_epoch_estimate: number | null; images: Record<string, DecisionImageState> };
export type TrainingTelemetryAsset = { key: string; training_filename: string; project_filename: string; preview_url: string };
export type TrainingSample = { filename: string; epoch: number | null; sample_index: number | null; seed: number | null; timestamp: string | null; source_dir: string; url: string };
export type TrainingTelemetry = { run_id: string; status: string; software: Record<string, unknown>; files: Record<string, boolean>; metrics: TrainingMetric[]; trajectories: Record<string, PerImageLossRow[]>; decision_history: DecisionSnapshot[]; problem_images: Record<string, unknown> | null; events: Array<Record<string, unknown>>; assets?: TrainingTelemetryAsset[]; samples: TrainingSample[]; console_tail: string[] };
export type TrainingStatus = { run: RunInfo; worker_alive: boolean };
export type QwenTask = { label: string; instruction: string; max_tokens: number };
export type CaptioningOptions = { providers: Array<| { id: "qwen"; name: string; tasks: Record<string, QwenTask>; default_task: string; default_model: string; default_processor: string; default_revision: string; supports_instruction_override: true; supports_arbitrary_model: true } | { id: "florence"; name: string; models: string[]; default_model: string; tasks: string[]; default_task: string; supports_instruction_override: false }> };
export type CaptionGenerateRequest = { provider: "qwen" | "florence"; model?: string; model_path?: string; processor?: string; revision?: string; task?: string; instruction?: string; max_tokens?: number; trigger_word?: string; add_trigger_word?: boolean; save?: boolean };
export type Preferences = { qwen_caption_model: string; qwen_caption_processor: string; qwen_caption_revision: string; caption_model_dir: string };
export type AssetTrainingPolicy = "automatic" | "always_train";
export type AutoRecaptionPolicy = "automatic" | "hold" | "never";
export type ProjectAssetPolicy = { training_policy: AssetTrainingPolicy; auto_recaption_policy: AutoRecaptionPolicy; updated_at?: string };
export type ProjectRevisionPolicy = { revision: string; updated_at?: string | null; caption_validation: { protected_phrases: string[]; spellcheck_enabled: boolean; accepted_words: string[] }; assets: Record<string, ProjectAssetPolicy> };
export type ModelDownloadJob = { id: string; kind: string; repo_id: string; revision: string; model_dir: string; select_when_complete: boolean; status: "queued" | "running" | "complete" | "failed"; phase: string; created_at: string; started_at: string | null; finished_at: string | null; path: string | null; selected: boolean; error: string | null };
export type SourceArchiveImport = { path: string; archive_name: string; file_count: number; image_count: number; caption_count: number };
export type TrainingFilenameScheme = "lineage" | "sequential";
export type TrainingFilenamePolicy = { mode: "original" | "normalized"; basename: string; digits: number; scheme: TrainingFilenameScheme; extension: "png"; assignments: Record<string, string>; updated_at?: string | null };
export type TrainingFilenameRow = { asset_id?: string; project_filename: string; training_filename: string; asset_kind: "source" | "derived"; origin?: string; parent_asset_id?: string | null; parent_filename?: string };
export type TrainingFilenameState = { policy: TrainingFilenamePolicy; rows: TrainingFilenameRow[] };

async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { "Content-Type": "application/json", ...(init?.headers || {}) }, ...init }); if (!response.ok) { let detail = `${response.status} ${response.statusText}`; try { const body = await response.json(); if (body?.detail) detail = body.detail; } catch {} throw new Error(detail); } return response.json() as Promise<T>; }
async function apiForm<T>(url: string, form: FormData): Promise<T> { const response = await fetch(url, { method: "POST", body: form }); if (!response.ok) { let detail = `${response.status} ${response.statusText}`; try { const body = await response.json(); if (body?.detail) detail = body.detail; } catch {} throw new Error(detail); } return response.json() as Promise<T>; }

export function listProjects() { return api<ProjectInfo[]>("/api/projects"); }
export function createProject(args: { name: string; source_path: string; trigger_word?: string; description?: string; selected_filenames?: string[] }) { return api<ProjectCreateResult>("/api/projects", { method: "POST", body: JSON.stringify(args) }); }
export function getProject(projectId: string) { return api<ProjectInfo>(`/api/projects/${encodeURIComponent(projectId)}`); }
export function getProjectRevision(projectId: string, revisionId: string) { return api<ProjectRevision>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}`); }
export function createProjectRevision(projectId: string, args: { name: string; model_family: string; parent_revision?: string; import_id?: string }) { return api<ProjectRevision>(`/api/projects/${encodeURIComponent(projectId)}/revisions`, { method: "POST", body: JSON.stringify(args) }); }
export function importProjectArchive(file: File) { const form = new FormData(); form.append("archive", file); return apiForm<ProjectInfo>("/api/projects/import", form); }
export function projectExportUrl(projectId: string) { return `/api/projects/${encodeURIComponent(projectId)}/export`; }
export function uploadSourceArchive(destination: string, file: File) { const form = new FormData(); form.append("destination", destination); form.append("archive", file); return apiForm<SourceArchiveImport>("/api/sources/archive", form); }
export function getProjectRevisionPolicy(projectId: string, revisionId: string) { return api<ProjectRevisionPolicy>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/policy`); }
export function updateCaptionValidationPolicy(projectId: string, revisionId: string, args: { protected_phrases?: string[]; spellcheck_enabled?: boolean; accepted_words?: string[] }) { return api<ProjectRevisionPolicy>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/policy/caption-validation`, { method: "PUT", body: JSON.stringify(args) }); }
export function updateProjectAssetPolicy(projectId: string, revisionId: string, filename: string, args: { training_policy?: AssetTrainingPolicy; auto_recaption_policy?: AutoRecaptionPolicy }) { return api<ProjectRevisionPolicy>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/policy/assets/${encodeURIComponent(filename)}`, { method: "PUT", body: JSON.stringify(args) }); }
export function getImagePrepState(projectId: string, revisionId: string) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep`); }
export function setImageInclusion(projectId: string, revisionId: string, filenames: string[], included: boolean) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/inclusion`, { method: "PUT", body: JSON.stringify({ filenames, included }) }); }
export function setAllImageInclusion(projectId: string, revisionId: string, included: boolean) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/inclusion-all`, { method: "PUT", body: JSON.stringify({ filenames: [], included }) }); }
export function setGlobalImageTransform(projectId: string, revisionId: string, transform: ImageTransform) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/global-transform`, { method: "PUT", body: JSON.stringify({ transform }) }); }
export function setTrainingResolution(projectId: string, revisionId: string, policy: Partial<TrainingResolutionPolicy>) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/training-resolution`, { method: "PUT", body: JSON.stringify({ policy }) }); }
export function getTrainingFilenames(projectId: string, revisionId: string) { return api<TrainingFilenameState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/training-filenames`); }
export function previewTrainingFilenames(projectId: string, revisionId: string, args: { mode?: "original" | "normalized"; basename: string; digits: number; scheme: TrainingFilenameScheme }) { return api<TrainingFilenameState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/training-filenames/preview`, { method: "POST", body: JSON.stringify({ mode: args.mode ?? "normalized", basename: args.basename, digits: args.digits, scheme: args.scheme }) }); }
export function updateTrainingFilenames(projectId: string, revisionId: string, args: { mode: "original" | "normalized"; basename?: string; digits?: number; scheme?: TrainingFilenameScheme; rebuild?: boolean }) { return api<TrainingFilenameState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/training-filenames`, { method: "PUT", body: JSON.stringify({ basename: "", digits: 4, scheme: "lineage", rebuild: false, ...args }) }); }
export function setAssetImageTransform(projectId: string, revisionId: string, filename: string, override: ImageTransform) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/assets/${encodeURIComponent(filename)}/transform`, { method: "PUT", body: JSON.stringify({ override }) }); }
export function preparedAssetPreviewUrl(projectId: string, revisionId: string, filename: string) { return `/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/assets/${encodeURIComponent(filename)}/prepared-preview`; }
export function deleteDerivativeAsset(projectId: string, revisionId: string, filename: string) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/assets/${encodeURIComponent(filename)}`, { method: "DELETE" }); }
export function createManualCrop(projectId: string, revisionId: string, filename: string, aspectRatio: string, crop: { x: number; y: number; width: number; height: number }) { return api<{ asset: ProjectAsset; state: ImagePrepState }>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/manual-crops`, { method: "POST", body: JSON.stringify({ filename, aspect_ratio: aspectRatio, crop }) }); }
export function proposeFaceCrops(projectId: string, revisionId: string, filenames: string[], aspectRatio: string, paddingPercent: number) { return api<{ proposals: FaceCropProposal[] }>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/face-crops/propose`, { method: "POST", body: JSON.stringify({ filenames, aspect_ratio: aspectRatio, padding_percent: paddingPercent }) }); }
export function acceptFaceCrops(projectId: string, revisionId: string, proposals: FaceCropProposal[]) { return api<{ assets: ProjectAsset[]; state: ImagePrepState }>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/face-crops/accept`, { method: "POST", body: JSON.stringify({ proposals }) }); }
export function queueImagePrepOperation(projectId: string, revisionId: string, filenames: string[], operation: Record<string, unknown>) { return api<ImagePrepState>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/prep/operations`, { method: "POST", body: JSON.stringify({ filenames, operation }) }); }
export function updateProjectCaption(projectId: string, revisionId: string, filename: string, args: { caption: string; reason?: string; metadata?: Record<string, unknown>; materialize?: boolean; run_id?: string }) { return api<{ filename: string; caption: string; changed: boolean; materialized: boolean }>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/captions/${encodeURIComponent(filename)}`, { method: "PUT", body: JSON.stringify(args) }); }
export function materializeProjectCaptions(projectId: string, revisionId: string) { return api<{ revision: string; written: number }>(`/api/projects/${encodeURIComponent(projectId)}/revisions/${encodeURIComponent(revisionId)}/materialize-captions`, { method: "POST" }); }
export function prepareRun(projectId: string, args: { name: string; model_family: string; dataset_revision: string; trigger_word?: string; config?: Record<string, unknown> }) { return api<RunInfo>(`/api/projects/${encodeURIComponent(projectId)}/runs`, { method: "POST", body: JSON.stringify(args) }); }
export function getRun(projectId: string, runId: string) { return api<RunInfo>(`/api/projects/${encodeURIComponent(projectId)}/runs/${encodeURIComponent(runId)}`); }
export function appendRunEvent(projectId: string, runId: string, type: string, payload: Record<string, unknown> = {}) { return api<Record<string, unknown>>(`/api/projects/${encodeURIComponent(projectId)}/runs/${encodeURIComponent(runId)}/events`, { method: "POST", body: JSON.stringify({ type, payload }) }); }
export function startTraining(projectId: string, runId: string) { return api<TrainingStatus>(`/api/projects/${encodeURIComponent(projectId)}/runs/${encodeURIComponent(runId)}/training/start`, { method: "POST" }); }
export function getTrainingStatus(projectId: string, runId: string) { return api<TrainingStatus>(`/api/projects/${encodeURIComponent(projectId)}/runs/${encodeURIComponent(runId)}/training/status`); }
export function getRunTelemetry(projectId: string, runId: string) { return api<TrainingTelemetry>(`/api/projects/${encodeURIComponent(projectId)}/runs/${encodeURIComponent(runId)}/telemetry`); }
export function inspectDataset(path: string) { return api<DatasetInfo>("/api/datasets/inspect", { method: "POST", body: JSON.stringify({ path }) }); }
export function saveCaption(datasetId: string, filename: string, caption: string) { return api<{ filename: string; caption: string }>(`/api/datasets/${datasetId}/captions/${encodeURIComponent(filename)}`, { method: "PUT", body: JSON.stringify({ caption }) }); }
export function getCaptioningOptions() { return api<CaptioningOptions>("/api/captioning/options"); }
export function generateCaption(datasetId: string, filename: string, request: CaptionGenerateRequest) { return api<{ filename: string; caption: string; saved: boolean; provider: string }>(`/api/datasets/${datasetId}/captions/${encodeURIComponent(filename)}/generate`, { method: "POST", body: JSON.stringify(request) }); }
export function unloadCaptionModels() { return api<{ unloaded: string[] }>("/api/captioning/unload", { method: "POST" }); }
export function getPreferences() { return api<Preferences>("/api/preferences"); }
export function savePreferences(preferences: Preferences) { return api<Preferences>("/api/preferences", { method: "PUT", body: JSON.stringify(preferences) }); }
export function downloadQwenModel(args: { repo_id: string; revision?: string; model_dir?: string; use_as_qwen_caption_model?: boolean }) { return api<ModelDownloadJob>("/api/models/qwen/download", { method: "POST", body: JSON.stringify(args) }); }
export function getModelDownload(jobId: string) { return api<ModelDownloadJob>(`/api/models/downloads/${encodeURIComponent(jobId)}`); }
